Ft     = 48000;           % Sampling Frequency in Hz
Fstop1 = 7200;            % First Stopband Frequency in Hz 
Fpass1 = 9600;            % First Passband Frequency in Hz 
Fpass2 = 12000;           % Second Passband Frequency in Hz 
Fstop2 = 14400;           % Second Stopband Frequency in Hz 
Dstop1 = 0.001;           % First Stopband Attenuation 
Dpass  = 0.01;      % Passband Ripple 
Dstop2 = 0.0001;          % Second Stopband Attenuation 
dens   = 20;              % Density Factor

f=[7200 9600 12000 14400];
a=[0 1 0];
dev=[0.001 0.01 0.0001];

[n,fo,ao,w] = firpmord(f,a,dev,Ft);
b = firpm(n,fo,ao,w);

Hd = dfilt.dffir(b)


set(Hd,'Arithmetic', 'fixed', ...  
    'CoeffWordLength', 12, ...    
    'CoeffAutoScale', true, ...   
    'Signed',         true, ...   
    'InputWordLength', 12, ...    
    'InputFracLength', 11, ...    
    'FilterInternals',  'SpecifyPrecision', ...    
    'OutputWordLength',  26, ...    
    'OutputFracLength',  24, ...    
    'ProductWordLength', 24, ...    
    'ProductFracLength', 24, ...    
    'AccumWordLength',   26, ...    
    'AccumFracLength',   24, ...    
    'RoundMode',...
    'convergent', ... 
    'OverflowMode', 'Wrap');

fvtool(Hd);